AY2425S1-CS2103-F12-3/tp

- docs/_config.yml
> Update Site Title

- docs/DeveloperGuide.md
Updated Developers Guide Use Cases by adding in the use cases of adding a vendor, updating a vendor and tagging a vendor.
Fixes #41
> Update Developers Guide Use Case

- docs/DeveloperGuide.md
Updated Developers Guide, removed UI Elements
Fixes #45
> Branch update developers guide

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/storage/JsonAddressBookStorage.java
> Fix corruption fail safe

- src/main/java/seedu/address/MainApp.java
- src/main/java/seedu/address/storage/JsonAddressBookStorage.java
> Fix Data Corruption

- src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
- src/test/java/seedu/address/logic/commands/EditCommandTest.java
- src/test/java/seedu/address/logic/commands/FindCommandTest.java
- src/test/java/seedu/address/logic/commands/ListCommandTest.java
- src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
- src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
> Comment test file to suppress failing CI

- src/main/java/seedu/address/logic/commands/FindTagCommand.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
- src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
- src/test/java/seedu/address/logic/commands/FindTagsCommandTest.java
- src/test/java/seedu/address/model/person/TagContainsKeywordsPredicateTest.java
> Branch filter by tag

- docs/DeveloperGuide.md
- docs/UserGuide.md
> Update developer guide

- src/main/java/seedu/address/ui/HelpWindow.java
> Update Help function

- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/commands/RatingCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/AddressBookParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/logic/parser/RatingCommandParser.java
- src/main/java/seedu/address/model/restaurant/Rating.java
- src/main/java/seedu/address/model/restaurant/Restaurant.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedRestaurant.java
- src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
- src/main/java/seedu/address/ui/RestaurantCard.java
- src/main/resources/view/PersonListCard.fxml
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditRestaurantDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/storage/JsonAdaptedRestaurantTest.java
- src/test/java/seedu/address/testutil/EditRestaurantDescriptorBuilder.java
- src/test/java/seedu/address/testutil/RestaurantBuilder.java
- src/test/java/seedu/address/testutil/TypicalRestaurants.java
Add Ratings Feature under MVP
Change the seed data to accommodate ratings
> Add Ratings Feature

- docs/diagrams/ModelClassDiagram.puml
> Update Class Diagram

- src/main/java/seedu/address/logic/parser/EditCommandParser.java
> Add logger in EditCommandParser

- docs/DeveloperGuide.md
- docs/diagrams/BetterModelClassDiagram.puml
- docs/diagrams/FindTagSequenceDiagram.puml
Fixes #109 
Added FindTagCommand UML diagram
> Branch update uml diagram

- src/test/java/seedu/address/logic/commands/FindCommandTest.java
> Fix test for find command

- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
> Add exit button in Help Window

- src/test/java/seedu/address/model/restaurant/AddressTest.java
- src/test/java/seedu/address/model/restaurant/EmailTest.java
- src/test/java/seedu/address/model/restaurant/NameTest.java
- src/test/java/seedu/address/model/restaurant/PhoneTest.java
Added test cases for hash code consistency, coverage for methods is now 100% for Name, Email, Address and Phone Test files
Fixes #201
> Added HashCode Test Cases

- src/test/java/seedu/address/logic/parser/FavouriteCommandParserTest.java
- src/test/java/seedu/address/logic/parser/UnfavouriteCommandParserTest.java
> Add Favourite/Unfavourite Parser test

- src/main/java/seedu/address/logic/commands/WelcomeCommand.java
- src/main/java/seedu/address/model/restaurant/UniqueRestaurantList.java
- src/main/java/seedu/address/ui/HelpWindow.java
- src/main/resources/view/GrubTheme.css
- src/test/java/seedu/address/logic/commands/UnfavouriteCommandTest.java
Fixes #159 
Adds sorting to the favourite/unfavourite/add and edit commands. 
After each restaurant added/edited, it'll be sorted in alphabetical order.
> Add support for sorting 

- src/main/resources/view/MainWindow.fxml
Previous increase in https://github.com/AY2425S1-CS2103-F12-3/tp/pull/218 was too much
> Decrease size of main window

- src/main/resources/view/ResultDisplay.fxml
Fixes #236, #245, #253, #259 used a VBox to ensure that the button is not overlapping the textarea, obscuring it 
Fixes #243, the textarea and the button is now not stacked on each other, thus not covering each other
> Fix horizontal scroll issue

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/FindPriceCommandParser.java
Fixes #281 
Fixes #270 
Fixes #251 
Added a check on Price Command ensuring inputs are only the allowed price label.
> Add alphaneumeric check for Price

- docs/DeveloperGuide.md
- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/FindTagCommandParser.java
- src/test/java/seedu/address/logic/parser/FindTagCommandParserTest.java
Reverts AY2425S1-CS2103-F12-3/tp#292
> Revert "Fixed user mix up for tags price command"

- src/main/java/seedu/address/logic/Messages.java
- src/main/java/seedu/address/logic/parser/FindPriceCommandParser.java
Reverts AY2425S1-CS2103-F12-3/tp#293
> Revert "Add alphaneumeric check for Price"

- src/main/java/seedu/address/logic/Messages.java
Reverts AY2425S1-CS2103-F12-3/tp#239
> Revert "Fix rating message bug"
